#!/usr/bin/env python3
# -*- coding: utf-8 -*-
'''
Generate a strong password.

Usage:
  generate-password [-u] [-l] [-n] [-s] [-h] [-len=<length>]

Options:
  -u, --no-uppercase     Exclude uppercase letters.
  -l, --no-lowercase     Exclude lowercase letters.
  -n, --no-numbers       Exclude numbers.
  -s, --no-symbols       Exclude special symbols.
  -len=<length>          Password length (default: 12).
  -h, --help             Show this help message and exit.
'''

import random
import string
from icecream import ic
from docopt import docopt


def generatePassword(uppercase=True, lowercase=True, numbers=True, symbols=False, length=12):
    password = ''
    alphabet = ''

    if uppercase:
        alphabet += string.ascii_uppercase
        password += random.choice(string.ascii_uppercase)
    if lowercase:
        alphabet += string.ascii_lowercase
        password += random.choice(string.ascii_lowercase)
    if numbers:
        alphabet += string.digits
        password += random.choice(string.digits)
    if symbols:
        alphabet += string.punctuation
        password += random.choice(string.punctuation)

    if not alphabet:
        raise ValueError('You must enable at least one character set.')

    remaining_length = length - len(password)
    if remaining_length <= 0:
        return password

    password += ''.join(random.choice(alphabet) for _ in range(remaining_length))
    return ''.join(random.sample(password, len(password)))  # shuffle the password


if __name__ == '__main__':
    arguments = docopt(__doc__)

    uppercase = not arguments['--no-uppercase']
    lowercase = not arguments['--no-lowercase']
    numbers = not arguments['--no-numbers']
    symbols = not arguments['--no-symbols']
    length = int(arguments.get('-len') or 12)

    try:
        password = generatePassword(uppercase, lowercase, numbers, symbols, length)
        print(password)
    except ValueError as e:
        print(f'Error: {e}')
