#!/usr/bin/env python3
# -*- coding: utf-8 -*-
'''
Generate a strong password.

Usage:
  generate-password [-u] [-l] [-n] [-s] [--len <length>]

Options:
  -u, --no-uppercase           Exclude uppercase letters. (default: false)
  -l, --no-lowercase           Exclude lowercase letters. (default: false)
  -n, --no-numbers             Exclude numbers. (default: false)
  -s, --no-symbols             Exclude special symbols. (default: false)
  -e <length, --len <length>   Password length (default: 12).
  -h, --help                   Show this help message and exit.

Example:
  $ generate-password
  TEm{m3{;Csvm

  $ generate-password -s -e 4
  Va9U
'''

import random
import string
from icecream import ic
from docopt import docopt


def generatePassword(uppercase=True, lowercase=True, numbers=True, symbols=False, length=12):
    password = ''
    alphabet = ''

    if uppercase:
        alphabet += string.ascii_uppercase
        password += random.choice(string.ascii_uppercase)
    if lowercase:
        alphabet += string.ascii_lowercase
        password += random.choice(string.ascii_lowercase)
    if numbers:
        alphabet += string.digits
        password += random.choice(string.digits)
    if symbols:
        alphabet += string.punctuation
        password += random.choice(string.punctuation)

    if not alphabet:
        raise ValueError('You must enable at least one character set.')

    remainingLength = length - len(password)
    if remainingLength <= 0:
        return password

    password += ''.join(random.choice(alphabet) for _ in range(remainingLength))
    return ''.join(random.sample(password, len(password)))  # shuffle the password


if __name__ == '__main__':
    args = docopt(__doc__)

    ic(args)

    uppercase = not args['--no-uppercase']
    lowercase = not args['--no-lowercase']
    numbers = not args['--no-numbers']
    symbols = not args['--no-symbols']
    length = int(args.get('--len') or 12)

    try:
        password = generatePassword(uppercase, lowercase, numbers, symbols, length)
        print(password)
    except ValueError as e:
        print(f'Error: {e}')
